//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konu()
        {
            this.Yorums = new HashSet<Yorum>();
        }
    
        public int KonuID { get; set; }
        public int KategoriID { get; set; }
        public int UyeID { get; set; }
        public string KonuBaslik { get; set; }
        public string KonuIcerik { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Uyeler Uyeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorums { get; set; }
    }
}
