//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int YorumID { get; set; }
        public int UyeID { get; set; }
        public int KonuID { get; set; }
        public string YorumIcerigi { get; set; }
        public System.DateTime YorumZamani { get; set; }
    
        public virtual Konu Konu { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
